# =======================================================================================
# Options from "Search Providers" Tab
# =======================================================================================

from .._viewmodel import Block
from .._viewmodel import OptionString, OptionNumber, OptionPassword, OptionBool, OptionPath, OptionList

def _(x):
    """ required just for marking translatable strings"""
    return x

def reg(tabname, register_block_cb, register_options_cb):

    register_block_cb(tabname,
        Block('all', caption=_("All"), options=register_options_cb(

    # =======================================================================================
    # =======================================================================================
    # =======================================================================================

            OptionNumber('ALBUM_COMPLETION_PCT', 'Advanced', 80,
                label=_('zzALBUM_COMPLETION_PCTzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('AUTOWANT_ALL', 'General', 0,
                label=_('zzAUTOWANT_ALLzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('AUTOWANT_MANUALLY_ADDED', 'General', 1,
                label=_('zzAUTOWANT_MANUALLY_ADDEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('AUTOWANT_UPCOMING', 'General', 1,
                label=_('zzAUTOWANT_UPCOMINGzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('AUTO_ADD_ARTISTS', 'General', 1,
                label=_('zzAUTO_ADD_ARTISTSzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('BOXCAR_ENABLED', 'Boxcar', 0,
                label=_('zzBOXCAR_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('BOXCAR_ONSNATCH', 'Boxcar', 0,
                label=_('zzBOXCAR_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('BOXCAR_TOKEN', 'Boxcar', '',
                label=_('zzBOXCAR_TOKENzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),



            OptionPath('CUE_SPLIT_FLAC_PATH', 'General', '',
                label=_('zzCUE_SPLIT_FLAC_PATHzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionPath('CUE_SPLIT_SHNTOOL_PATH', 'General', '',
                label=_('zzCUE_SPLIT_SHNTOOL_PATHzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionNumber('CUSTOMAUTH', 'General', 0,
                label=_('zzCUSTOMAUTHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('CUSTOMHOST', 'General', 'localhost',
                label=_('zzCUSTOMHOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('CUSTOMPASS', 'General', '',
                label=_('zzCUSTOMPASSzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('CUSTOMPORT', 'General', 5000,
                label=_('zzCUSTOMPORTzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('CUSTOMSLEEP', 'General', 1,
                label=_('zzCUSTOMSLEEPzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('CUSTOMUSER', 'General', '',
                label=_('zzCUSTOMUSERzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('DO_NOT_PROCESS_UNMATCHED', 'General', 0,
                label=_('zzDO_NOT_PROCESS_UNMATCHEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('EMAIL_ENABLED', 'Email', 0,
                label=_('zzEMAIL_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('EMAIL_FROM', 'Email', '',
                label=_('zzEMAIL_FROMzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('EMAIL_ONSNATCH', 'Email', 0,
                label=_('zzEMAIL_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionPassword('EMAIL_SMTP_PASSWORD', 'Email', '',
                label=_('zzEMAIL_SMTP_PASSWORDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('EMAIL_SMTP_PORT', 'Email', 25,
                label=_('zzEMAIL_SMTP_PORTzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('EMAIL_SMTP_SERVER', 'Email', '',
                label=_('zzEMAIL_SMTP_SERVERzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('EMAIL_SMTP_USER', 'Email', '',
                label=_('zzEMAIL_SMTP_USERzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('EMAIL_SSL', 'Email', 0,
                label=_('zzEMAIL_SSLzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('EMAIL_TLS', 'Email', 0,
                label=_('zzEMAIL_TLSzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('EMAIL_TO', 'Email', '',
                label=_('zzEMAIL_TOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('EXTRAS', 'General', '',
                label=_('zzEXTRASzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionList('EXTRA_NEWZNABS', 'Newznab', '',
                label=_('zzEXTRA_NEWZNABSzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionList('EXTRA_TORZNABS', 'Torznab', [],
                label=_('zzEXTRA_TORZNABSzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionNumber('FREEZE_DB', 'General', 0,
                label=_('zzFREEZE_DBzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('GROWL_ENABLED', 'Growl', 0,
                label=_('zzGROWL_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('GROWL_HOST', 'Growl', '',
                label=_('zzGROWL_HOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('GROWL_ONSNATCH', 'Growl', 0,
                label=_('zzGROWL_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('GROWL_PASSWORD', 'Growl', '',
                label=_('zzGROWL_PASSWORDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionBool('HEADPHONES_INDEXER', 'General', False,
                label=_('zzHEADPHONES_INDEXERzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionString('HPPASS', 'General', '',
                label=_('zzHPPASSzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('HPUSER', 'General', '',
                label=_('zzHPUSERzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('IDTAG', 'Beets', 0,
                label=_('zzIDTAGzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionList('IGNORED_FILES', 'Advanced', [],
                label=_('zzIGNORED_FILESzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionList('IGNORED_FOLDERS', 'Advanced', [],
                label=_('zzIGNORED_FOLDERSzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionNumber('INCLUDE_EXTRAS', 'General', 0,
                label=_('zzINCLUDE_EXTRASzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('JOURNAL_MODE', 'Advanced', 'wal',
                label=_('zzJOURNAL_MODEzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('KAT', 'Kat', 0,
                label=_('zzKATzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('KAT_PROXY_URL', 'Kat', '',
                label=_('zzKAT_PROXY_URLzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('KAT_RATIO', 'Kat', '',
                label=_('zzKAT_RATIOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),


            OptionString('LASTFM_USERNAME', 'General', '',
                label=_('zzLASTFM_USERNAMEzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('LIBRARYSCAN', 'General', 1,
                label=_('zzLIBRARYSCANzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('LMS_ENABLED', 'LMS', 0,
                label=_('zzLMS_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('LMS_HOST', 'LMS', '',
                label=_('zzLMS_HOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),

            OptionNumber('MININOVA', 'Mininova', 0,
                label=_('zzMININOVAzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('MININOVA_RATIO', 'Mininova', '',
                label=_('zzMININOVA_RATIOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('MIRROR', 'General', 'musicbrainz.org',
                label=_('zzMIRRORzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),

            OptionBool('MPC_ENABLED', 'MPC', False,
                label=_('zzMPC_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionPath('MUSIC_DIR', 'General', '',
                label=_('zzMUSIC_DIRzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionNumber('NEWZNAB', 'Newznab', 0,
                label=_('zzNEWZNABzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('NEWZNAB_APIKEY', 'Newznab', '',
                label=_('zzNEWZNAB_APIKEYzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('NEWZNAB_ENABLED', 'Newznab', 1,
                label=_('zzNEWZNAB_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('NEWZNAB_HOST', 'Newznab', '',
                label=_('zzNEWZNAB_HOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('NMA_APIKEY', 'NMA', '',
                label=_('zzNMA_APIKEYzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('NMA_ENABLED', 'NMA', 0,
                label=_('zzNMA_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('NMA_ONSNATCH', 'NMA', 0,
                label=_('zzNMA_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('NMA_PRIORITY', 'NMA', 0,
                label=_('zzNMA_PRIORITYzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('NZBSORG', 'NZBsorg', 0,
                label=_('zzNZBSORGzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('NZBSORG_HASH', 'NZBsorg', '',
                label=_('zzNZBSORG_HASHzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('NZBSORG_UID', 'NZBsorg', '',
                label=_('zzNZBSORG_UIDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('OFFICIAL_RELEASES_ONLY', 'General', 0,
                label=_('zzOFFICIAL_RELEASES_ONLYzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('OLDPIRATEBAY', 'Old Piratebay', 0,
                label=_('zzOLDPIRATEBAYzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('OLDPIRATEBAY_RATIO', 'Old Piratebay', '',
                label=_('zzOLDPIRATEBAY_RATIOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('OLDPIRATEBAY_URL', 'Old Piratebay', '',
                label=_('zzOLDPIRATEBAY_URLzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('OMGWTFNZBS', 'omgwtfnzbs', 0,
                label=_('zzOMGWTFNZBSzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('OMGWTFNZBS_APIKEY', 'omgwtfnzbs', '',
                label=_('zzOMGWTFNZBS_APIKEYzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('OMGWTFNZBS_UID', 'omgwtfnzbs', '',
                label=_('zzOMGWTFNZBS_UIDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('OSX_NOTIFY_APP', 'OSX_Notify', '/Applications/Headphones',
                label=_('zzOSX_NOTIFY_APPzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('OSX_NOTIFY_ENABLED', 'OSX_Notify', 0,
                label=_('zzOSX_NOTIFY_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('OSX_NOTIFY_ONSNATCH', 'OSX_Notify', 0,
                label=_('zzOSX_NOTIFY_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('PIRATEBAY', 'Piratebay', 0,
                label=_('zzPIRATEBAYzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('PIRATEBAY_PROXY_URL', 'Piratebay', '',
                label=_('zzPIRATEBAY_PROXY_URLzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('PIRATEBAY_RATIO', 'Piratebay', '',
                label=_('zzPIRATEBAY_RATIOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('PLEX_CLIENT_HOST', 'Plex', '',
                label=_('zzPLEX_CLIENT_HOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('PLEX_ENABLED', 'Plex', 0,
                label=_('zzPLEX_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('PLEX_NOTIFY', 'Plex', 0,
                label=_('zzPLEX_NOTIFYzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('PLEX_PASSWORD', 'Plex', '',
                label=_('zzPLEX_PASSWORDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('PLEX_SERVER_HOST', 'Plex', '',
                label=_('zzPLEX_SERVER_HOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('PLEX_TOKEN', 'Plex', '',
                label=_('zzPLEX_TOKENzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('PLEX_UPDATE', 'Plex', 0,
                label=_('zzPLEX_UPDATEzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('PLEX_USERNAME', 'Plex', '',
                label=_('zzPLEX_USERNAMEzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),

            OptionNumber('PROWL_ENABLED', 'Prowl', 0,
                label=_('zzPROWL_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('PROWL_KEYS', 'Prowl', '',
                label=_('zzPROWL_KEYSzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('PROWL_ONSNATCH', 'Prowl', 0,
                label=_('zzPROWL_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('PROWL_PRIORITY', 'Prowl', 0,
                label=_('zzPROWL_PRIORITYzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('PUSHALOT_APIKEY', 'Pushalot', '',
                label=_('zzPUSHALOT_APIKEYzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('PUSHALOT_ENABLED', 'Pushalot', 0,
                label=_('zzPUSHALOT_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('PUSHALOT_ONSNATCH', 'Pushalot', 0,
                label=_('zzPUSHALOT_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('PUSHBULLET_APIKEY', 'PushBullet', '',
                label=_('zzPUSHBULLET_APIKEYzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('PUSHBULLET_DEVICEID', 'PushBullet', '',
                label=_('zzPUSHBULLET_DEVICEIDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('PUSHBULLET_ENABLED', 'PushBullet', 0,
                label=_('zzPUSHBULLET_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('PUSHBULLET_ONSNATCH', 'PushBullet', 0,
                label=_('zzPUSHBULLET_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('PUSHOVER_APITOKEN', 'Pushover', '',
                label=_('zzPUSHOVER_APITOKENzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('PUSHOVER_ENABLED', 'Pushover', 0,
                label=_('zzPUSHOVER_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('PUSHOVER_KEYS', 'Pushover', '',
                label=_('zzPUSHOVER_KEYSzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('PUSHOVER_ONSNATCH', 'Pushover', 0,
                label=_('zzPUSHOVER_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('PUSHOVER_PRIORITY', 'Pushover', 0,
                label=_('zzPUSHOVER_PRIORITYzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),

            OptionBool('RENAME_FROZEN', 'General', True,
                label=_('zzRENAME_FROZENzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionBool('RENAME_UNPROCESSED', 'General', True,
                label=_('zzRENAME_UNPROCESSEDzz'),
                caption=_(''),
                tooltip=_(''),
            ),

            OptionNumber('RUTRACKER', 'Rutracker', 0,
                label=_('zzRUTRACKERzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('RUTRACKER_PASSWORD', 'Rutracker', '',
                label=_('zzRUTRACKER_PASSWORDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('RUTRACKER_RATIO', 'Rutracker', '',
                label=_('zzRUTRACKER_RATIOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('RUTRACKER_USER', 'Rutracker', '',
                label=_('zzRUTRACKER_USERzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('SONGKICK_APIKEY', 'Songkick', 'nd1We7dFW2RqxPw8',
                label=_('zzSONGKICK_APIKEYzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('SONGKICK_ENABLED', 'Songkick', 1,
                label=_('zzSONGKICK_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('SONGKICK_FILTER_ENABLED', 'Songkick', 0,
                label=_('zzSONGKICK_FILTER_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('SONGKICK_LOCATION', 'Songkick', '',
                label=_('zzSONGKICK_LOCATIONzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('STRIKE', 'Strike', 0,
                label=_('zzSTRIKEzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('STRIKE_RATIO', 'Strike', '',
                label=_('zzSTRIKE_RATIOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('SUBSONIC_ENABLED', 'Subsonic', 0,
                label=_('zzSUBSONIC_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('SUBSONIC_HOST', 'Subsonic', '',
                label=_('zzSUBSONIC_HOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('SUBSONIC_PASSWORD', 'Subsonic', '',
                label=_('zzSUBSONIC_PASSWORDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('SUBSONIC_USERNAME', 'Subsonic', '',
                label=_('zzSUBSONIC_USERNAMEzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('SYNOINDEX_ENABLED', 'Synoindex', 0,
                label=_('zzSYNOINDEX_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('TORRENT_REMOVAL_INTERVAL', 'General', 720,
                label=_('zzTORRENT_REMOVAL_INTERVALzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('TORZNAB', 'Torznab', 0,
                label=_('zzTORZNABzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('TORZNAB_APIKEY', 'Torznab', '',
                label=_('zzTORZNAB_APIKEYzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('TORZNAB_ENABLED', 'Torznab', 1,
                label=_('zzTORZNAB_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('TORZNAB_HOST', 'Torznab', '',
                label=_('zzTORZNAB_HOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('TWITTER_ENABLED', 'Twitter', 0,
                label=_('zzTWITTER_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('TWITTER_ONSNATCH', 'Twitter', 0,
                label=_('zzTWITTER_ONSNATCHzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('TWITTER_PASSWORD', 'Twitter', '',
                label=_('zzTWITTER_PASSWORDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('TWITTER_PREFIX', 'Twitter', 'Headphones',
                label=_('zzTWITTER_PREFIXzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('TWITTER_USERNAME', 'Twitter', '',
                label=_('zzTWITTER_USERNAMEzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionBool('VERIFY_SSL_CERT', 'Advanced', True,
                label=_('zzVERIFY_SSL_CERTzz'),
                caption=_(''),
                tooltip=_(''),
            ),
            OptionNumber('WAFFLES', 'Waffles', 0,
                label=_('zzWAFFLESzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('WAFFLES_PASSKEY', 'Waffles', '',
                label=_('zzWAFFLES_PASSKEYzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('WAFFLES_RATIO', 'Waffles', '',
                label=_('zzWAFFLES_RATIOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('WAFFLES_UID', 'Waffles', '',
                label=_('zzWAFFLES_UIDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('WAIT_UNTIL_RELEASE_DATE', 'General', 0,
                label=_('zzWAIT_UNTIL_RELEASE_DATEzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionNumber('WHATCD', 'What.cd', 0,
                label=_('zzWHATCDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('WHATCD_PASSWORD', 'What.cd', '',
                label=_('zzWHATCD_PASSWORDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('WHATCD_RATIO', 'What.cd', '',
                label=_('zzWHATCD_RATIOzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionString('WHATCD_USERNAME', 'What.cd', '',
                label=_('zzWHATCD_USERNAMEzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('XBMC_ENABLED', 'XBMC', 0,
                label=_('zzXBMC_ENABLEDzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('XBMC_HOST', 'XBMC', '',
                label=_('zzXBMC_HOSTzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('XBMC_NOTIFY', 'XBMC', 0,
                label=_('zzXBMC_NOTIFYzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('XBMC_PASSWORD', 'XBMC', '',
                label=_('zzXBMC_PASSWORDzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),
            OptionNumber('XBMC_UPDATE', 'XBMC', 0,
                label=_('zzXBMC_UPDATEzz'),
                caption=_(''),
                tooltip=_(''),
                minvalue=None,
                maxvalue=None
            ),
            OptionString('XBMC_USERNAME', 'XBMC', '',
                label=_('zzXBMC_USERNAMEzz'),
                caption=_(''),
                tooltip=_(''),
                maxlength=None
            ),

    # =======================================================================================
    # =======================================================================================
    # =======================================================================================

        ))
    )
