"""Constants used by Mutagen."""

GENRES = [
    u"Blues",
    u"Classic Rock",
    u"Country",
    u"Dance",
    u"Disco",
    u"Funk",
    u"Grunge",
    u"Hip-Hop",
    u"Jazz",
    u"Metal",
    u"New Age",
    u"Oldies",
    u"Other",
    u"Pop",
    u"R&B",
    u"Rap",
    u"Reggae",
    u"Rock",
    u"Techno",
    u"Industrial",
    u"Alternative",
    u"Ska",
    u"Death Metal",
    u"Pranks",
    u"Soundtrack",
    u"Euro-Techno",
    u"Ambient",
    u"Trip-Hop",
    u"Vocal",
    u"Jazz+Funk",
    u"Fusion",
    u"Trance",
    u"Classical",
    u"Instrumental",
    u"Acid",
    u"House",
    u"Game",
    u"Sound Clip",
    u"Gospel",
    u"Noise",
    u"Alt. Rock",
    u"Bass",
    u"Soul",
    u"Punk",
    u"Space",
    u"Meditative",
    u"Instrumental Pop",
    u"Instrumental Rock",
    u"Ethnic",
    u"Gothic",
    u"Darkwave",
    u"Techno-Industrial",
    u"Electronic",
    u"Pop-Folk",
    u"Eurodance",
    u"Dream",
    u"Southern Rock",
    u"Comedy",
    u"Cult",
    u"Gangsta",
    u"Top 40",
    u"Christian Rap",
    u"Pop/Funk",
    u"Jungle",
    u"Native American",
    u"Cabaret",
    u"New Wave",
    u"Psychadelic",
    u"Rave",
    u"Showtunes",
    u"Trailer",
    u"Lo-Fi",
    u"Tribal",
    u"Acid Punk",
    u"Acid Jazz",
    u"Polka",
    u"Retro",
    u"Musical",
    u"Rock & Roll",
    u"Hard Rock",
    u"Folk",
    u"Folk/Rock",
    u"National Folk",
    u"Swing",
    u"Fusion",
    u"Bebob",
    u"Latin",
    u"Revival",
    u"Celtic",
    u"Bluegrass",
    u"Avantgarde",
    u"Gothic Rock",
    u"Progressive Rock",
    u"Psychadelic Rock",
    u"Symphonic Rock",
    u"Slow Rock",
    u"Big Band",
    u"Chorus",
    u"Easy Listening",
    u"Acoustic",
    u"Humour",
    u"Speech",
    u"Chanson",
    u"Opera",
    u"Chamber Music",
    u"Sonata",
    u"Symphony",
    u"Booty Bass",
    u"Primus",
    u"Porn Groove",
    u"Satire",
    u"Slow Jam",
    u"Club",
    u"Tango",
    u"Samba",
    u"Folklore",
    u"Ballad",
    u"Power Ballad",
    u"Rhythmic Soul",
    u"Freestyle",
    u"Duet",
    u"Punk Rock",
    u"Drum Solo",
    u"A Capella",
    u"Euro-House",
    u"Dance Hall",
    u"Goa",
    u"Drum & Bass",
    u"Club-House",
    u"Hardcore",
    u"Terror",
    u"Indie",
    u"BritPop",
    u"Negerpunk",
    u"Polsk Punk",
    u"Beat",
    u"Christian Gangsta Rap",
    u"Heavy Metal",
    u"Black Metal",
    u"Crossover",
    u"Contemporary Christian",
    u"Christian Rock",
    u"Merengue",
    u"Salsa",
    u"Thrash Metal",
    u"Anime",
    u"Jpop",
    u"Synthpop"
    ]
"""The ID3v1 genre list."""
